version: "3.1"

language: en  

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7 
- name: DucklingEntityExtractor
  url: "http://localhost:8000"
  dimensions: ["time", "number"]
  timeout: 3

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 15
  epochs: 100

assistant_id: 20231102-123230-legato-lose



